### ISSUE TITLE
code for chebylighter

### ISSUE THREAD

**Issue by eeerpjw** [dawnlh/awesome-low-light-image-enhancement#11]
Hi Zhihong,

Could you please add the code for "ChebyLighter: Optimal Curve Estimation for Low-light Image Enhancement, ACM MM 2022" 
This is the GitHub link [code](https://github.com/eeerpjw/ChebyLighter)

Many Thanks~

**Comment by dawnlh** [comment]
Of course, thanks for your sharing!
