### ISSUE TITLE
Could you add our AAAI23 paper to the table?

### ISSUE THREAD

**Issue by laulampaul** [dawnlh/awesome-low-light-image-enhancement#13]
Low-Light Video Enhancement with Synthetic Event Guidance (AAAI), 2023
Lin Liu, Junfeng An, Jianzhuang Liu, Shanxin Yuan, Xiangyu Chen, Wengang Zhou, Houqiang Li, Yanfeng Wang, Qi Tian

Thank you so much!

**Comment by laulampaul** [comment]
paper: https://arxiv.org/abs/2208.11014

**Comment by dawnlh** [comment]
@laulampaul Of course, BTW, have you released the code?

**Comment by laulampaul** [comment]
> @laulampaul Of course, BTW, have you released the code?

the code link is here, https://gitee.com/mindspore/models/tree/master/research/cv/LLVE-SEG
The code is currently undergoing official review and may be available for viewing through this link soon.
