### ISSUE TITLE
TMM 2023 "Glow in the Dark: Low-Light Image Enhancement with External Memory"

### ISSUE THREAD

**Issue by Lineves7** [dawnlh/awesome-low-light-image-enhancement#15]
Could you please add this work :
Glow in the Dark: Low-Light Image Enhancement with External Memory
Published in TMM, 2023
note: EMNet
paper: [https://ieeexplore.ieee.org/document/10177254](https://ieeexplore.ieee.org/document/10177254)
Code: [https://github.com/Lineves7/EMNet](https://github.com/Lineves7/EMNet)

Thank you very much.

**Comment by dawnlh** [comment]
The paper have been added, thanks for your sharing.
