### ISSUE TITLE
Add new paper

### ISSUE THREAD

**Issue by YuyangYin** [dawnlh/awesome-low-light-image-enhancement#16]
Could you please add this work :
CLE Diffusion: Controllable Light Enhancement Diffusion Model
Published in ACMMM 2023
note: CLE Diffusion
paper: https://arxiv.org/abs/2308.06725
Code:  https://github.com/YuyangYin/CLEDiffusion
Web：https://yuyangyin.github.io/CLEDiffusion/
Thank you very much.

**Comment by dawnlh** [comment]
The paper has been added, thanks for your sharing!

**Comment by dawnlh** [comment]
The paper has been added, thans for your sharing!
