### ISSUE TITLE
Add a new paper.

### ISSUE THREAD

**Issue by cuiziteng** [dawnlh/awesome-low-light-image-enhancement#22]
Thanks for your really awesome repo! Could you please add our AAAI 2024 work? 

This is low-light enhancement & exposure correction + NeRF

Title: Aleth-NeRF: Illumination Adaptive NeRF with Concealing Field Assumption

Published in AAAI 2024

Name: Aleth-NeRF
Code: https://github.com/cuiziteng/Aleth-NeRF
Website: https://cuiziteng.github.io/Aleth_NeRF_web/

**Comment by cuiziteng** [comment]
Additionally, this paper propose a paired low-light & normal-light multi-view dataset (for NeRF under low-light conditions), names LOM dataset.

<a href="https://drive.google.com/file/d/1orgKEGApjwCm6G8xaupwHKxMbT2s9IAG/view?usp=sharing">[google drive]</a> or 
<a href="https://pan.baidu.com/s/1BGfstg2IpN0JZBlVaMG-eQ">[baiduyun (passwd: ve1t)]</a>

I would be greatly thanks if you could also add this dataset ~

**Comment by dawnlh** [comment]
Thanks for your sharing, the items have been added.
