### ISSUE TITLE
Integrating Graph Convolution Into a Deep Multilayer Framework for Low-Light Image Enhancement

### ISSUE THREAD

**Issue by santoshpanda1995** [dawnlh/awesome-low-light-image-enhancement#25]
Please add this paper. 

S. K. Panda and P. K. Sa, "Integrating Graph Convolution Into a Deep Multilayer Framework for Low-Light Image Enhancement," in IEEE Sensors Letters, vol. 8, no. 5, pp. 1-4, May 2024, Art no. 7002404, doi: 10.1109/LSENS.2024.3380889.

The Github link is https://github.com/santoshpanda1995/LightweightGCN-Model

The paper link is https://doi.org/10.1109/LSENS.2024.3380889

**Comment by dawnlh** [comment]
Thank you. It has been added.
