### ISSUE TITLE
Request to Add New Paper

### ISSUE THREAD

**Issue by xingyumex** [dawnlh/awesome-low-light-image-enhancement#29]
Thank you for your outstanding work on this repository. I would like to kindly request if you could add our recent publication to the repository. Below are the details:

Title: LoLi-IEA: low-light image enhancement algorithm
Published In: SPIE, Applications of Machine Learning 2023
Name: LoLi-IEA
Paper Link: [LoLi-IEA Paper](https://www.spiedigitallibrary.org/conference-proceedings-of-spie/12675/1267512/LoLi-IEA-low-light-image-enhancement-algorithm/10.1117/12.2677422.short#_=_)
Code: [LoLi-IEA Code Repository](https://github.com/xingyumex/LoLi-IEA)

Thank you very much for your consideration.

**Comment by dawnlh** [comment]
Thanks for sharing. The paper has been added.
