### ISSUE TITLE
New 2025 paper, "CDAN: Convolutional Dense Attention-Guided Network for Low-Light Image Enhancement"

### ISSUE THREAD

**Issue by SinaRaoufi** [dawnlh/awesome-low-light-image-enhancement#30]
I would like to suggest adding a new paper to this repository:

**Learning-based method**
**Year:** 2025
**Pub:** Digital Signal Processing
**Paper:** CDAN: Convolutional dense attention-guided network for low-light image enhancement
**Link:** [pdf](https://www.sciencedirect.com/science/article/abs/pii/S1051200424004275) [code](https://github.com/SinaRaoufi/CDAN)
**Note:** CDAN

**Comment by dawnlh** [comment]
Thanks for sharing. The paper has been added.
