### ISSUE TITLE
AMSR cause the image brightness reversal

### ISSUE THREAD

**Issue by hsqaihkl** [dawnlh/awesome-low-light-image-enhancement#6]
Hi ，I run the function of amsr.m
but the result of the image is brightness reversal.
You can use the "memorial.hdr" to run you will find this.

**Comment by dawnlh** [comment]
Hi~
The code of AMSR was collected from the Internet, I tested it with "memorial.hdr" and got similar results as another method shown in [this link](https://blog.csdn.net/weixin_34302561/article/details/93818167). I cannot guarantee the correctness of the code in AMSR. If you find it wrong, pull requests are welcome.

**Comment by dawnlh** [comment]
![image](https://user-images.githubusercontent.com/19143656/153422370-3aca2620-37b1-454c-85e1-3c12166acabb.png)

**Comment by hsqaihkl** [comment]
Hi,I just download the code from your respository on github and then to run it.you can run the code with the hdr image in accessory .

















At 2022-02-10 21:55:47, "dawnlh" ***@***.***> wrote:

Hi~
The code of AMSR was collected from the Internet, I tested it with "memorial.hdr" and got similar results as another method shown in this link. I cannot guarantee the correctness of the code in AMSR. If you find it wrong, pull requests are welcome.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
