### ISSUE TITLE
ICCV 2021: Multitask AET with Orthogonal Tangent Regularity for Dark Object Detection

### ISSUE THREAD

**Issue by cuiziteng** [dawnlh/awesome-low-light-image-enhancement#7]
This paper is about low-light object detection, and accepted by ICCV main conference, could you please add it, thanks a lot!

The code [link](https://github.com/cuiziteng/ICCV_MAET)
The paper [link](https://openaccess.thecvf.com/content/ICCV2021/html/Cui_Multitask_AET_With_Orthogonal_Tangent_Regularity_for_Dark_Object_Detection_ICCV_2021_paper.html)

**Comment by dawnlh** [comment]
Thanks for your sharing, I have updated the list.
