### ISSUE TITLE
how does MSR output the light map?

### ISSUE THREAD

**Issue by sunohm** [dawnlh/awesome-low-light-image-enhancement#9]
Hello, how does MSR output the light map? In the multiscaleRetinex (I, method, varargin) method, is the light map directly output with OUT=T in SSlog?

**Comment by WilsonAir** [comment]
邮件已收到，感谢您的来信，我将尽快给您回复。魏后胜I have received your email. Thank you for your letter. I will reply to you as soon as possible.Housheng Wei

**Comment by sunohm** [comment]
The email has been received. I look forward to your reply.




light&amp;￡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dawnlh/awesome-low-light-image-enhancement"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dawnlh/awesome-low-light-image-enhancement] how does MSR output the light map? (Issue #9)





 邮件已收到，感谢您的来信，我将尽快给您回复。魏后胜I have received your email. Thank you for your letter. I will reply to you as soon as possible.Housheng Wei
